### ISSUE TITLE
Can runBNG correct the inner contig error with hybrid assembly pipeline？

### ISSUE THREAD

**Issue by Mr-Inamn** [AppliedBioinformatics/runBNG#11]
Hi Andy,
Can runBNG automatically correct the inner contig error with hybrid assembly pipeline？I used your pipeline and found it does has this function.

**Comment by yyx8671** [comment]
Hi @Mr-Inamn, 

Sorry for the delayed reply. Yes, runBNG can correct the inner contig errors, but it needs some parameter tuning by the users to meet their expectations.

Cheers,
Andy
