### ISSUE TITLE
hybrid scaffolding, -f final assembled cmap file

### ISSUE THREAD

**Issue by liu-xingliang** [AppliedBioinformatics/runBNG#12]
Hi,

I am trying to do hybrid scaffolding using runBNG hybrid, I am not quite sure what file should I feed to -f option.

I previously assumed that it is the final output file, but it seems not, because if I specify a new file name which is not existent, runBNG will complain.

Do I have to run runBNG denovo first to get this file and feed it in runBNG hybrid?

Thanks a lot.

bless~

**Comment by yyx8671** [comment]
Hi @liuxl18-hku, 

If you have already got a denovo assembled cmap file, you need to use this file. If you don't have such a cmap file, please try to denovo assemble your optical maps first using such as 'runBNG denovo'.

Cheers,
Andy

**Comment by liu-xingliang** [comment]
Hi @yyx8671 ,

OIC, sure, will do that. May I know how long it will take if I specify 16 threads for human data.

bless~
Xingliang

**Comment by yyx8671** [comment]
Hi @liuxl18-hku, 

Many things can affect the speed of running and it pretty much depends on the I/O of your server and the density of the nicking site.  I assume that it will take 3-5 days.

Cheers,
Andy

**Comment by liu-xingliang** [comment]
Hi @yyx8671 

Yes, fully understand, sorry for the non-specific question. Around half to one week is OK for us.

Thank you very much for your help!

bless~
Xingliang

**Comment by liu-xingliang** [comment]
Hi @yyx8671 ,

Sorry for bothering you again.

I have finished the `runBNG denovo` on the the test dataset, and I assumed that I should use the following file to feed -f of `runBNG hybrid`?

`$denovo_out_dir/contigs/exp_refineFinal1/EXP_REFINEFINAL1.cmap`

and for `runBNG hybrid`, if I want to find the scaffolded fasta, I assumed that I should use the following:

`$hybrid_out/hybrid_scaffolds/EXP_REFINEFINAL1_bppAdjust_cmap_Test_fa_NGScontigs_HYBRID_SCAFFOLD.fasta`

bless~
Xingliang

**Comment by yyx8671** [comment]
Hi @liuxl18-hku, 

Yes, you may want to use the cmap file to start your hybrid scaffolding. The scaffolded fasta file is the one you specified. You may want to combine the scaffolded fasta and the non-scaffolded fasta to finalised your assembly.

Cheers,
Andy

**Comment by liu-xingliang** [comment]
Hi @yyx8671 ,

Sure, I will merge the scaffolded and non-scaffolded fasta.

Thank you very much for all your help!

bless~
Xingliang
