### ISSUE TITLE
Raw molecules input (although it's mentioned in #7)

### ISSUE THREAD

**Issue by liu-xingliang** [AppliedBioinformatics/runBNG#13]
Hi,

It's me again. I opened a new issue for working on one problem for one issue thread.

Although it's mentioned in #7 , I am still having a question about where should I get the raw molecular bnx for both runBNG denovo/hybrid.

In runBNG manual, the example name given for raw molecular bnx is `Molecules.bnx`. I am not sure I need to do the same thing as what suggested by [KSU pipeline] (https://github.com/i5K-KINBRE-script-share/Irys-scaffolding/blob/master/KSU_bioinfo_lab/assemble_XeonPhi/assemble_XeonPhi_LAB.md):

> To create a new Datasets directory like this, run "AutoDetect" on your data. Next import the needed flowcells into a new IrsyView workspace. After importing you need to click on each flowcell listed in the workspace to generate a Molecules.bnx file from the RawMolecules.bnx file.

Thank you very much!

bless~
Xingliang

**Comment by yyx8671** [comment]
Hi @liuxl18-hku, 

I asked the Bionano people about the difference between RawMolecules.bnx and Molecules.bnx. Here is the reply: 'There isn't a significant difference between RawMolecules and Molecules bnx files other than the filter that is applied when importing into IrysView. You can check what the filter setting is in IrysView under the View -> Options -> Detect tab.' 

By the way, how many bnx files do you have? If you have one, you may use it as the input. If you have multiple bnx files, you may want to merge them first.

Cheers,
Andy

**Comment by liu-xingliang** [comment]
Hi @yyx8671 

Thank you very much. In that case, I will try to use the RawMolecules bnx as it's not required to use Molecules.bnx for runBNG.

I only have one bnx file. FYI.

bless~
Xingliang
