### ISSUE TITLE
Hybrid_scaffolds assembly issue

### ISSUE THREAD

**Issue by Sparkle-27** [AppliedBioinformatics/runBNG#16]
Hi

I recently ran into a problem when running hybridScaffold.pl script, job stopped in align0 step without any error information, scripts as following:

Do you have any suggestion for these? Thanks in advance.

**Comment by yuxuanyuan** [comment]
Hi, 

Have you tried 'runBNG hybrid'?

Cheers,
Andy

**Comment by Sparkle-27** [comment]
Hi
Thanks for the software, I have successfully run denovo pipeline,but no CMAP result have been generated. Where could I find the denovo result? Thx
![QQ截图20190621230216](https://user-images.githubusercontent.com/21327136/59931940-a4993080-9478-11e9-957e-7f2a134d8423.png)

**Comment by yyx8671** [comment]
You may find the 'EXP_REFINEFINAL1.cmap' file at ./contigs/exp_refineFinal1

**Comment by Sparkle-27** [comment]
@yyx8671 
Hi
I could only find ./contigs/exp_unrefined/, multiple cmap file exist in the folder, Should I merge all the exp_unrefined_contig***.cmap files and how could i do that. Thx

**Comment by yyx8671** [comment]
@huanfa 
If you run 'runBNG denovo' successfully, the contigs folder will contain some folders like:
<img width="280" alt="Screen Shot" src="https://user-images.githubusercontent.com/17119749/59959298-1d36d600-94e7-11e9-8c03-64e89f9bd585.png">
May I please ask if you use the runBNG required Bionano tools and scripts? 

Cheers,
Andy

**Comment by huanfa** [comment]
@yyx8671 Yes, I did have use the bionano tools from Solve and scripts download from the website you provided. Here are my script:

- /home/usr/software/runBNG denovo \
- -s /home/usr/software/Solve3.3_10252018/scripts/ \
- -t /home/usr/software/Solve3.3_10252018/RefAligner/7915.7989rel/ \
- -b ${input_bnx} \
- -T 100 \
- -j 4 \
- -B 0 \
- -r ./refCMAP/pilon_3nd_BSPQI_0kb_0labels.cmap \
- -z 2500 \
- -o denovo 
-

The output folder seems not run completely:
![QQ截图20190622144808](https://user-images.githubusercontent.com/21327136/59960697-94c42f80-94fe-11e9-865c-fbbea9997cd7.png)

**Comment by Sparkle-27** [comment]
Hi
@yyx8671 
Thanks for your help, I have run the de novo pipeline successfully, but new error appears in  hybrid step.
Do you have any suggestions? Thx.

![QQ截图20190625152758](https://user-images.githubusercontent.com/21327136/60078076-d4d51d80-975d-11e9-9c2a-14345f0c0cb6.png)

**Comment by yyx8671** [comment]
@huanfa 
May I please know your settings in 'runBNG hybrid'?

**Comment by huanfa** [comment]
Here are my scripts:

- /home/usr/software/runBNG hybrid \
- -s /home/usr/software/Solve3.3_10252018/scripts/ \
- -t /home/usr/software/Solve3.3_10252018/RefAligner/7915.7989rel/ \
- -b /data/usr/data/2.DRC_Male_9B0026PA_DG-2RawMolecules.bnx \
- -r /home/usr/project/1_polish/pilon_3nd/pilon_3nd.fasta \
- -B 2 \
- -N 1 \
- -z 2500 \
- -f ./denovo/contigs/exp_refineFinal1/EXP_REFINEFINAL1.cmap \
- -o hybrid_bng \
- -T 40 \
- -M 300

**Comment by yyx8671** [comment]
@
Can you try ‘-B 1 -N 2’ ? or you may want to tune '-c -u -g -d and -p'

**Comment by Sparkle-27** [comment]
@yyx8671
Hi, thanks for the suggestions, I have tried '-B 1 N 2' and '-B 1 -N 1', but same error appeared. I guess parameters is not the reason why error appears. Is my input file format wrong? I have no idea, thanks a lot.

**Comment by yyx8671** [comment]
@huanfa 
Can you try to align your assembled cmap file to your NGS assembly using Irysview and to see if the quality of the BNG denovo assembly is good?

**Comment by huanfa** [comment]
Hi @yyx8671 
I have successfully run the pipeline,  Thanks for your paticent reply,  I found the script download from the website you provided /scripts/HybridScaffold/scripts/perl5/BNG/Utility.pm is different from Solve software,

**Comment by Sparkle-27** [comment]
Hi @yyx8671
I have successfully run the pipeline, Thanks for your patient reply, I found the script download from the website you provided /scripts/HybridScaffold/scripts/perl5/BNG/Utility.pm is different from Solve software
