### ISSUE TITLE
Can I run runBNG on a system with glibc-2.14?

### ISSUE THREAD

**Issue by wangzhennan14** [AppliedBioinformatics/runBNG#17]
Hi，
   When I run runBNG, it seems that the version of my glibc was low, but the system I used can not upgrade. Can I run runBNG on my system? Could you give me another version of runBNG which could run on glibc-2.15? Thank you very much!
Wang

**Comment by yyx8671** [comment]
Hi @wangzhennan14,

The version of glibc is required by the Bionao tools. I have not tested version 2.14. Probably you can use the test data provided in the package to have a try.

Cheers,
Andy
