### ISSUE TITLE
UnsubmittedJobs Problem while running 'runBNG denovo'

### ISSUE THREAD

**Issue by onkar2470** [AppliedBioinformatics/runBNG#19]
Hi,
I am running '**runBNG denovo**' command to covert my raw **.bnx file into .cmap** file (i.e. Rough Assembly) on a **server**
But while processing sortBNX job, i am encountering **UInsubmittedJobs problem**.
Job is not being submitted
Trying to run command:
**./runBNG denovo -b RawMolecules.bnx -t /Solve3.5.1_01142020/RefAligner/1.0/avx2/ -s /Solve3.5.1_01142020/Pipeline/1.0/ -T 30 -j 15 -l 180 -z 480 -o denovo2**

But getting:
The number of threads for each subjob is: 15
The number of iterations is: 5
False Positive Density (/100Kb) [FP]: 1.5
False Negative Rate (%/100) [FN]: 0.15
ScalingSD (Kb^1/2) [sd]: 0.0
SiteSD (Kb) [sf]: 0.2
RelativeSD [sr]: 0.03
The genome size (Mb) is: 480
The output directory is: denovo2

  Prerun Tests:
	0 ERRORS
	2 WARNINGS

  WARNING: Disabling SV detection (-V, default ON) because no reference supplied, or invalid.
  WARNING: Disabling alignment of molecules vs reference (-m, default ON) because no reference supplied, or invalid.

Tools Version: N/A
Solve Version: N/A
Pipeline Version: 10322
RefAligner Version: 10436

Assembly ID: 100

  Pipeline start time: Fri Mar 20 00:17:09 2020

checkScanScaling: autoNoise= False
Not performing autoNoise (see -y): setting doScanScale = False, hence not using _rescaled.bnx for BNX splits
Executing stage number 1 : AutoNoise + SplitBNX

Molecule Stats (/bionano/denovo2/all.bnx):
Total number of molecules: 
Total length (Mbp)       : 
Average length (kbp)     :     
Molecule N50 (kbp)       :     
Label density (/100kb)   :     

Sorting bionano/denovo2/all.bnx into bionano/denovo2/all_sorted
 Starting Multi-Threaded Process: SortBNX
  Running 1 jobs with 30 threads, sleepTime=0.02
SortBNX: jobName= SortBNX: not on cluster: availableThreads= 30, sJob.maxThreads= 47 (skipping)
SortBNX: waited 1800.0 seconds for job completion: **UnsubmittedJobs= 1**, ActiveJobs= 0, FinishedJobs= 0
SortBNX: jobName= SortBNX: not on cluster: availableThreads= 30, sJob.maxThreads= 47 (skipping)
SortBNX: waited 3600.0 seconds for job completion: UnsubmittedJobs= 1, ActiveJobs= 0, FinishedJobs= 0

Am I missing some parameter?
Please help
Thanx,
Onkar

**Comment by yuxuanyuan** [comment]
Hi @onkar2470 , 

Thanks for using 'runBNG'. I noticed this issue when using the latest Bionano scripts. The current 'runBNG' is suitable for the old **IrysSolve scripts** instead of the **BionanoSolve scripts**. 

You may consider adding more options in 'runBNG' at line 1404 or 1408 to customise the number of threads used for each subjob, as the new BionanoSolve is designed for the Saphyr workstation/cluster. Please also note that the **xml file** has been changed as well. 

If you are in a hurry to run your jobs, please consider using 'pipelineCL.py' directly from Solve3.xxx. I'm rewriting a  'runBNG_saphyr' script, but it will take a while.

Cheers,
Andy

**Comment by onkar2470** [comment]
Hi Andy,
I appreciate your quick reply
I have used '**pipelineCL.py**' directly  also from **Solve3.5.1**  and used **optArguments_haplotype_saphyr.xml** with -R parameter but getting same problem 
My data generated using Saphyr

Should I use the previous version of Solve?

Thanx,
Onkar

**Comment by yuxuanyuan** [comment]
Hi Onkar, 

I haven't tested the Saphyr data using the old pipeline as at the time of writing 'runBNG' we had no such data. You may try the old scripts, but I cannot guarantee the accuracy of the result.

For the xml file, please ensure you require a haplotype phased assembly or not. You may try to set '-j', '-je', '-jp', '-J', ' -TJ' and  '-Te' to run your job (for instance setting 6 for all) when using 'pipelineCL.py'.

Please let me know if it works.

Cheers,
Andy

**Comment by onkar2470** [comment]
Hi Andy,
I set '-j', '-je', '-jp', '-J', ' -TJ' and '-Te' all these parameters to 6 as you suggested and its working!!!
This command is running
Hope it will run without interruption
Thank you so much for your help and such a quick response
