### ISSUE TITLE
runBNG can't be run with python3

### ISSUE THREAD

**Issue by yzhang18** [AppliedBioinformatics/runBNG#24]
Hello,

I have installed bionano solve in a container. When I ran the command:
	./runBNG denovo \
	                -t      /home/bionano/tools/pipeline/Solve3.6.1_11162020/RefAligner/1.0 \
	                -s      /home/bionano/tools/pipeline/Solve3.6.1_11162020/ \
	                -b      ~/Data/A673_bionano/EwingSarcoma_November2019/EwingsSarcoma_Solve3.4_pipeline_results/output/all.bnx \
	                -M      yes \
	                -a      15 \
	                -T      1 \
	                -j      1 \
	                -z      3137 \
	                -r      ~/Data/A673_bionano/runBNG_rslt/hg19_DLE1_20kb_5labels.cmap \
	                -o      ~/Data/A673_bionano/runBNG_rslt

I got the following error:
		Traceback (most recent call last):
		  File "/home/bionano/tools/pipeline/Solve3.6.1_11162020/Pipeline/1.0/pipelineCL.py", line 30, in <module>
		    import Pipeline
		  File "/home/bionano/tools/pipeline/Solve3.6.1_11162020/Pipeline/11162020/Pipeline.py", line 19, in <module>
		    import AlignModule as alignment
		  File "/home/bionano/tools/pipeline/Solve3.6.1_11162020/Pipeline/11162020/AlignModule.py", line 5, in <module>
		    import Multithreading as mthreading
		  File "/home/bionano/tools/pipeline/Solve3.6.1_11162020/Pipeline/11162020/Multithreading.py", line 369
		    print "WARNING: cannot identify thread overload from clusterArgs and adjust -TotalThreads:", sJob.jobName # DEBUG
		                                                                                              ^
		SyntaxError: Missing parentheses in call to 'print'. Did you mean print("WARNING: cannot identify thread overload from clusterArgs and adjust -TotalThreads:", sJob.jobName # DEBUG)?
		Could not log status: pipeline exit 2886804

Looks like it doesn't like the syntax from pyton3.
Is run BNG only compatible with python2?

Thanks,
Yuan

**Comment by yyx8671** [comment]
Hi @yzhang18, 

Python 2.7.5 and above is recommended for running Bionano Solve (not python3). Btw, you may use mutiple threads to run the denovo assembly, otherwise, it may take a long time to complete your task.

**Comment by yzhang18** [comment]
Hello Andy,

Thanks for your quick response.

I’ve also built a bionano container with python 2.7.15. I had trouble installing llvmlite in the container. Could you help? I’m not good at python. The error message is:


Collecting llvmlite>=0.27.0dev0

  Downloading llvmlite-0.32.1.tar.gz (104 kB)

Collecting enum34

  Downloading enum34-1.1.10-py2-none-any.whl (11 kB)

Collecting six

  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)

Building wheels for collected packages: llvmlite

  Building wheel for llvmlite (setup.py): started

  Building wheel for llvmlite (setup.py): finished with status 'error'

  ERROR: Command errored out with exit status 1:

   command: /usr/local/bin/python2.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-AvHwIV/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-AvHwIV/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-AqTtjy

       cwd: /tmp/pip-install-AvHwIV/llvmlite/

  Complete output (7 lines):

  running bdist_wheel

  /usr/local/bin/python2.7 /tmp/pip-install-AvHwIV/llvmlite/ffi/build.py

    File "/tmp/pip-install-AvHwIV/llvmlite/ffi/build.py", line 122

      raise ValueError(msg.format(_ver_check_skip)) from e

                                                       ^

  SyntaxError: invalid syntax

  error: command '/usr/local/bin/python2.7' failed with exit status 1

  ----------------------------------------

  ERROR: Failed building wheel for llvmlite

  Running setup.py clean for llvmlite

Failed to build llvmlite

Installing collected packages: numpy, six, singledispatch, funcsigs, llvmlite, enum34, numba

    Running setup.py install for llvmlite: started

    Running setup.py install for llvmlite: finished with status 'error'

    ERROR: Command errored out with exit status 1:

     command: /usr/local/bin/python2.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-AvHwIV/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-AvHwIV/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-U1Eig0/install-record.txt --single-version-externally-managed --home /tmp/pip-target-At5z2f --compile --install-headers /tmp/pip-target-At5z2f/include/python/llvmlite

         cwd: /tmp/pip-install-AvHwIV/llvmlite/

    Complete output (10 lines):

    running install

    running build

    got version from file /tmp/pip-install-AvHwIV/llvmlite/llvmlite/_version.py {'version': '0.32.1', 'full': 'aa11b129c0b55973067422397821ae6d44fa5e70'}

    running build_ext

    /usr/local/bin/python2.7 /tmp/pip-install-AvHwIV/llvmlite/ffi/build.py

      File "/tmp/pip-install-AvHwIV/llvmlite/ffi/build.py", line 122

        raise ValueError(msg.format(_ver_check_skip)) from e

                                                         ^

    SyntaxError: invalid syntax

    error: command '/usr/local/bin/python2.7' failed with exit status 1

    ----------------------------------------

ERROR: Command errored out with exit status 1: /usr/local/bin/python2.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-AvHwIV/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-AvHwIV/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-U1Eig0/install-record.txt --single-version-externally-managed --home /tmp/pip-target-At5z2f --compile --install-headers /tmp/pip-target-At5z2f/include/python/llvmlite Check the logs for full command output.

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.

Thanks,
Yuan


From: Andy Yuan ***@***.***>
Reply-To: AppliedBioinformatics/runBNG ***@***.***>
Date: Wednesday, April 7, 2021 at 10:34 AM
To: AppliedBioinformatics/runBNG ***@***.***>
Cc: "Zhang, Yuan" ***@***.***>, Mention ***@***.***>
Subject: Re: [AppliedBioinformatics/runBNG] runBNG can't be run with python3 (#24)

[WARNING: External Email - Use Caution]


Hi @yzhang18<https://urldefense.com/v3/__https:/github.com/yzhang18__;!!ODYTt7Uqo6LDP14!3ea-jLt0WK2O6rtkJX40tVaqmjs852pzIq-QJBtl06QgLpVLlN6td1fhV_W1rHiYXnUfQQRweOA$>,

Python 2.7.5 and above is recommended for running Bionano Solve (not python3). Btw, you may use mutiple threads to run the denovo assembly, otherwise, it may take a long time to complete your task.

**Comment by yuxuanyuan** [comment]
Hi @yzhang18, 

Have you tried to install using conda? 

Cheers,
Andy

**Comment by yzhang18** [comment]
Hello Andy,


No I didn’t try conda install.
I ran the script bng-install.sh which uses pip install.

I have another question: in the script, python3 packages are also installed. Are they not used? Is there effort to make the script work with python 3?

Thanks,
Yuan

________________________________

**Comment by yyx8671** [comment]
Hi @yzhang18, 

I thought you were installing the packages for 'runBNG'. Actually, runBNG doesn't need any installation for ``Bionano Solve`` except some python2 packages and R packages. If you want to install ``Bionano Access`` on your server, you may contact 'support@bionanogenomics.com' for help.
