### ISSUE TITLE
examples & where to store BioNano scripts/tools

### ISSUE THREAD

**Issue by liuqianhn** [AppliedBioinformatics/runBNG#3]
Hi, may I know where to store BioNano scripts/tools so that runBNG can find them? Do you have examples how to runBNG? Thanks.

**Comment by yyx8671** [comment]
@liuqianhn For the settings and how to run 'runBNG', you may refer https://github.com/AppliedBioinformatics/runBNG/blob/master/Manual.md. The test data is available at https://github.com/AppliedBioinformatics/runBNG/tree/master/Examples. For the BioNano scripts and tools, you can download them to any directory on your Linux cluster, but give them a readable and executable permission.

**Comment by liuqianhn** [comment]
Hi Andy, thank you very much. 

May I know how can I run runBNG with glibc 2.14? I cannot install higher version of glibc in my system.

**Comment by yyx8671** [comment]
@liuqianhn Glibc is required by RefAligner/Assembler. I have tested the old version, such as 'glibc 2.11.3' on SUSE Linux and it works, but for other Linux system, such as CentOS, it may not work. 

The easy way to install 'glibc' is to use Linuxbrew, which I have indicated in the Manual. You may refer to it. 

If you don't want to install Linuxbrew, you may disable the code in 'runBNG' from line 92 to 108 by adding "#" to the very beginning of each line, and test whether the whole runBNG pipeline works properly on your system.

**Comment by liuqianhn** [comment]
Hi Andy, Thank you very much for your help. I used CentOS. I tried to used older version of RefAligner/Assembler. It could work with glibc 2.14. I will try your suggestions also. Thanks.
