### ISSUE TITLE
runBNG SV

### ISSUE THREAD

**Issue by kkuonjj** [AppliedBioinformatics/runBNG#4]
Hi, 

I'm a bit confused how to compare two different cmaps from individuals of the same species using your script. The -r option is clear to me, but where can I define the query cmap? Is it the 'full path to final assembled folder, such as *exp_refineFinal1.' as written in the help print out? Anyway, I tried both but it says 'Some compulsory option is not given please check as following:' 

My second question concerns the genome size. Do I need to estimate the genome size or should I give it the exact length in Mb that was assembled? 

Thank you very much for showing a simple example how I should set up the command for SV detection between two cmaps assembled from two individuals. 

cheers, 
j

**Comment by yyx8671** [comment]
Hi @kkuonjj, if you want to directly compare two cmap files, you may use 'runBNG compare'. If you want to find SVs in the query sample, you may use 'runBNG SV'. 

In the 'runBNG SV', except the '-b' option, others are all mandatory. You may check which option you have missed in your settings. For the '-f' option, it refers to the final denovo assembled folder. If you use 'runBNG denovo', the folder should be under the /path /to/your saved denovo assembly folder/contigs/exp_refineFinal1. 

For the genome size, I suggest using the estimated genome size.

Cheers,
Andy
