### ISSUE TITLE
Raw molecules input

### ISSUE THREAD

**Issue by ZihuaLiu666** [AppliedBioinformatics/runBNG#7]
Hi! I am so appreciated the software for bionano data analysis because it makes everything clear and easy to operate, comparing with KSU scripts and IrysView software! 
However, I am a little confused with the .bnx input for script MQR and script denovo.
1. MQR -b the raw molecule map file (Molecules.bnx) ---> if I have my .bnx files merged, should the -b input be merged_molecules.bnx?
2. The same question for denovo -b the raw molecule map file (Molecules.bnx) ---> I guess that it should be merged one.

And, I noticed that -r argument within denovo script should be the digested reference (.cmap), should the reference be the standard reference genome downloaded from NCBI or my raw PacBio assembled fasta file?

Thank you very much in advance and looking forward to your generous replies.

** btw, although I am an undergraduate student, I can understand the meaning of each step. The runBNG instruction is so friendly to naive practicer.

**Comment by yyx8671** [comment]
Thanks for using 'runBNG'. 
Sorry for the confusion. For the (-b), you need to give the final bnx file which you want to analyse. For the (-r), you may use your own assembly (I guess you want to use OM to improve your assembly). runBNG has provided a 'fa2cmap' function, which you may easily apply to get a cmap file.

**Comment by ZihuaLiu666** [comment]
Hi, thanks for your replies. The explanation is clear!  👍  The runBNG is running the _denovo_. Will I get a new fasta format file after the _denovo_ step? ;- )

**Comment by ZihuaLiu666** [comment]
fasta files will be acquired after the hybrid step ;-)
