### ISSUE TITLE
max and min avgintensity in bnxstats

### ISSUE THREAD

**Issue by JennyHTLee** [AppliedBioinformatics/runBNG#9]
Hello Andy,

Is there a small mistake in the bnxstats utility where "maxten" and "minten" should be reversed (Line 772 and 773 of runBNG script)?

My command: 
runBNG bnxstats -b Molecules.bnx -p expbnxstats -o ./

A snippet of output I get:
**Maximum avgIntensity is: 0.025330
Minimum avgIntensity is: 0.996826**
Average avgIntensity is: 0.265131

Thanks :) 

Cheers,
Jenny

**Comment by yyx8671** [comment]
Thanks Jenny, 

You are right. They should be reversed.

Cheers,
Andy
